---
- name: Recycle App Pools
  hosts: "{{ servers }}"
  gather_facts: no

  vars_files:
    - app_pools.yml

  tasks:
    - name: Stop App Pools
      win_webapppool:
        name: "{{ item }}"
        state: stopped
      loop: "{{ app_pools[apppool] }}"
      register: output

    - name: Check if App Pool is stopped
      win_shell: |
        Import-Module WebAdministration
        (Get-WebAppPoolState -Name "{{ item }}").Value
      loop: "{{ app_pools[apppool] }}"
      register: app_pool_state
      until: app_pool_state.stdout_lines[0] == "Stopped"
      retries: 5
      delay: 2

    - name: Start App Pools
      win_webapppool:
        name: "{{ item }}"
        state: started
      loop: "{{ app_pools[apppool] }}"
      register: output
      
    - name: Check current state of App Pools
      win_shell: |
        Import-Module WebAdministration
        (Get-WebAppPoolState -Name "{{ item }}").Value
      loop: "{{ app_pools[apppool] }}"
      register: app_pool_state_after_start

    - debug: var=output.stdout_lines
    - debug: var=app_pool_state_after_start.stdout_lines
    
