---
- name: Recycle App Pools
  hosts: "{{ servers }}"
  gather_facts: no
  serial: 2
  vars:
    App_PoolNames: ['AppPool1','AppPool2','AppPool3']
  tasks:
    - name: Stop App Pools
      win_webapppool:
        name: "{{ item }}"
        state: stopped
      loop: "{{ App_PoolNames }}"
      register: output
    - name: Check if App Pool is stopped
      win_shell: |
        Import-Module WebAdministration
        (Get-WebAppPoolState -Name "{{ item }}").Value
      loop: "{{ App_PoolNames }}"
      register: app_pool_state
      until: app_pool_state.stdout_lines[0] == "Stopped"
      retries: 5
      delay: 2
    - name: Start App Pools
      win_webapppool:
        name: "{{ item }}"
        state: started
      loop: "{{ App_PoolNames }}"
      register: output
    - debug: var=output.stdout_lines
