run-name: Recycling $ {{ github.event.inputs.apppool }} App Pools of $ {{ github.event.inputs.servers }}
on:
  workflow_dispatch:
    inputs:
      servers:
        type: choice
        required: true
        description: Server
        default: All
        options:
          - AllPROD
          - AllUAT
          - ServerUAT1
          - ServerUAT2
          - ServerPROD1
          - ServerPROD2
          
      apppool:
        type: choice
        required: true
        description: Application Pools
        default: All
        options:
          - All
          - AppPool1
          - AppPool2

jobs:
  recycle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install ansible

      - name: Run Ansible playbook
        run: ansible-playbook -i hosts.ini recycle_app_pools.yml -e "servers=${{ github.event.inputs.servers }} apppool=${{ github.event.inputs.apppool }}"
